### ISSUE TITLE
How can i solve this problems?

### ISSUE THREAD

**Issue by Melmet1** [Chrispresso/SnakeAI#12]
When I tried to run this program, this phrase followed by  'loading the generation : indv439'.

Traceback (most recent call last):
  File "C:\Snake\SnakeAI-master\mysnake.py", line 791, in <module>
    main()
  File "C:\Python_installer_3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python_installer_3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python_installer_3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python_installer_3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Snake\SnakeAI-master\mysnake.py", line 787, in main
    window = MainWindow(settings, show, fps)
  File "C:\Snake\SnakeAI-master\mysnake.py", line 95, in __init__
    individual = load_snake(f'./{data_folder}', indv, None)
  File "C:\Snake\SnakeAI-master\snake.py", line 476, in load_snake
    params[param] = np.load(os.path.join(population_folder, individual_name, fname))
  File "C:\Python_installer_3.10\lib\site-packages\numpy\lib\npyio.py", line 418, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

**Comment by Melmet1** [comment]
I solve this problems.
I delete .npy files in 'indv440' forder.
